# Generated by Django 6.0.5 on 2026-05-14 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_alter_dimcliente_data_cadastro'),
        ('servicos', '0003_dimservico_nome_servico'),
    ]

    operations = [
        migrations.CreateModel(
            name='FatoServico',
            fields=[
                ('nr_ordem_servico', models.AutoField(primary_key=True, serialize=False)),
                ('data_servico', models.DateTimeField(blank=True, null=True)),
                ('descricao_servico', models.CharField(max_length=200)),
                ('formas_pagamento', models.CharField(max_length=200)),
                ('valor_sugerido', models.FloatField(blank=True, null=True)),
                ('status_ordem_servico', models.CharField(choices=[('EM_ABERTO', 'Em Aberto'), ('CANCELADO', 'Cancelado'), ('EXECUTADO', 'Executado')], default='EM_ABERTO', max_length=100)),
                ('cod_cliente', models.ForeignKey(db_column='cod_cliente', on_delete=django.db.models.deletion.PROTECT, to='clientes.dimcliente', verbose_name='Cliente')),
                ('cod_servico', models.ForeignKey(db_column='cod_servico', on_delete=django.db.models.deletion.PROTECT, to='servicos.dimservico', verbose_name='Serviço')),
            ],
            options={
                'verbose_name': 'Ordem de Serviço',
                'verbose_name_plural': 'Ordens de Serviço',
                'db_table': 'FATO_SERVICOS',
            },
        ),
    ]
