# Generated by Django 6.0.5 on 2026-05-15 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='fatoservico',
                    name='observacao',
                    field=models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
        ),
    ]
