# Generated by Django 6.0.5 on 2026-05-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0002_fatoservico_observacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatoservico',
            name='nf',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nota Fiscal'),
        ),
    ]
