# Generated by Django 6.0.5 on 2026-05-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0003_fatoservico_nf'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatoservico',
            name='data_os',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data da OS'),
        ),
    ]
