# Generated by Django 6.0.5 on 2026-05-11 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DimCliente',
            fields=[
                ('cod_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('data_cadastro', models.DateTimeField(blank=True, null=True)),
                ('nome_completo', models.CharField(blank=True, max_length=100, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('endereco', models.CharField(blank=True, max_length=50, null=True)),
                ('numero', models.CharField(blank=True, max_length=5, null=True)),
                ('bairro', models.CharField(blank=True, max_length=30, null=True)),
                ('complemento', models.CharField(blank=True, max_length=30, null=True)),
                ('cidade', models.CharField(blank=True, max_length=30, null=True)),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('email_contato', models.EmailField(blank=True, max_length=45, null=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('celular', models.CharField(blank=True, max_length=15, null=True)),
                ('cpf', models.CharField(blank=True, max_length=15, null=True)),
                ('rg', models.CharField(blank=True, max_length=15, null=True)),
                ('tipo_pessoa', models.CharField(default='F', max_length=1)),
                ('cnpj', models.CharField(blank=True, max_length=20, null=True)),
                ('inscricao', models.CharField(blank=True, max_length=20, null=True)),
                ('nosconheceu', models.CharField(blank=True, max_length=45, null=True)),
                ('mailing', models.CharField(default='SIM', max_length=3)),
                ('observacao', models.CharField(blank=True, max_length=200, null=True)),
                ('suspenso', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'DIM_CLIENTES',
            },
        ),
    ]
