# Generated by Django 6.0.5 on 2026-05-12 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DimTipoServico',
            fields=[
                ('cod_tipo_servico', models.IntegerField(primary_key=True, serialize=False)),
                ('descricao_tipo_servico', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Serviço',
                'verbose_name_plural': 'Tipos de Serviço',
                'db_table': 'DIM_TIPO_SERVICOS',
            },
        ),
        migrations.CreateModel(
            name='DimServico',
            fields=[
                ('cod_servico', models.AutoField(primary_key=True, serialize=False)),
                ('descricao_servico', models.CharField(max_length=200)),
                ('valor_sugerido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('desativado', models.BooleanField(default=False)),
                ('cod_tipo_servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicos.dimtiposervico', verbose_name='Tipo de Serviço')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'db_table': 'DIM_SERVICOS',
            },
        ),
    ]
