# Generated by Django 6.0.5 on 2026-05-12 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='dimservico',
                    name='cod_tipo_servico',
                    field=models.ForeignKey(db_column='cod_tipo_servico', on_delete=django.db.models.deletion.PROTECT, to='servicos.dimtiposervico', verbose_name='Tipo de Serviço'),
                ),
            ],
        ),
    ]
