# Generated by Django 6.0.5 on 2026-05-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_alter_dimservico_cod_tipo_servico'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimservico',
            name='nome_servico',
            field=models.CharField(default='', max_length=100, verbose_name='Nome do Serviço'),
        ),
    ]
