# Generated by Django 6.0.5 on 2026-05-14 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_alter_dimcliente_data_cadastro'),
        ('ordens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DimContrato',
            fields=[
                ('nr_contrato', models.AutoField(primary_key=True, serialize=False)),
                ('nome_cliente', models.CharField(max_length=100)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('nome_arquivo', models.CharField(max_length=255)),
                ('status_contrato', models.CharField(choices=[('ATIVO', 'Ativo'), ('CANCELADO', 'Cancelado'), ('FINALIZADO', 'Finalizado')], default='ATIVO', max_length=50)),
                ('cod_cliente', models.ForeignKey(db_column='cod_cliente', on_delete=django.db.models.deletion.PROTECT, to='clientes.dimcliente', verbose_name='Cliente')),
                ('nr_ordem_servico', models.ForeignKey(db_column='nr_ordem_servico', on_delete=django.db.models.deletion.PROTECT, to='ordens.fatoservico', verbose_name='Ordem de Serviço')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'db_table': 'DIM_CONTRATOS',
            },
        ),
    ]
