# Generated by Django 6.0.5 on 2026-05-15 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimcontrato',
            name='arquivo_pdf',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
