# Generated by Django 6.0.5 on 2026-05-15 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0002_dimcontrato_arquivo_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dimcontrato',
            name='arquivo_pdf',
        ),
    ]
